# -*- coding: utf-8 -*-
"""Babylonbee.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17qfmCiYPWYczeFkXlCszjjPsOP1QxfY0
"""

import pandas as pd
from bs4 import BeautifulSoup
from urllib.request import Request, urlopen
import json

data = []
for i in range(1,400):
  site= "https://babylonbee.com/news?page=" + str(i)
  hdr = {'User-Agent': 'Mozilla/5.0'}
  req = Request(site,headers=hdr)
  page = urlopen(req)
  soup = BeautifulSoup(page)
  #print(soup)
  containers = soup.find_all("article-card")
  for article_card in containers:
    article_link = 'https://babylonbee.com' + article_card[":path"][1:-1]
    headline = article_card[":title"]
    print(headline)
    data.append({
            'article_link': article_link,
            'headline': headline,
            'is_sarcastic': 1,})
with open('babylonbee.json', 'w') as f:
    json.dump(data, f, indent = 3)

data = pd.read_json('babylonbee.json')
data.head(5)