# -*- coding: utf-8 -*-
"""Best_in_Au.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mOnHlfBZP-kjfM1OipxkJl3APl1fIlWB
"""

import pandas as pd
import requests
from bs4 import BeautifulSoup
import json
for  category in ["celebrity", "news", "interview", "movies", "entertainment", "technology", "sport", "politics"," "]:
  for page in range(1, 30):
      paper = "https://bestinau.com.au/category/"+ category +"/page/"+ str(page) +"/"
      response = requests.get(paper)
      soup = BeautifulSoup(response.content, "html.parser")
      titles = soup.findAll('h3', class_ = 'entry-title td-module-title')
      links = [link.find('a').attrs["href"] for link in titles]

      with open("/content/BestInAu.json", 'a') as f:
          for link in links:
              news = requests.get(link)
              soup = BeautifulSoup(news.content, "html.parser")
              title = soup.find("h1", class_ = "entry-title").text  
              data = {
                      "article_link" : link,
                      "headline" : title,
                      "is_sarcastic" : 0
                  }
              print(title)
              json.dump(data, f)
              f.write("\n")

import pandas as pd 
data_json = pd.read_json("/content/BestInAu.json", lines=True)
data_json