# -*- coding: utf-8 -*-
"""Bản sao của CityNews.ipynp

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zrQCdskdUa-3m3PCqSID1vC-PCkoWfzx
"""

import pandas as pd
import requests
from bs4 import BeautifulSoup
import json
for page in range(1, 500):
    print(page)
    paper = "https://toronto.citynews.ca/category/national/page/"+ str(page) + "/"
    response = requests.get(paper)
    soup = BeautifulSoup(response.content, "html.parser")
    titles = soup.findAll('div', class_ = 'col-lg-13 col-md-13 col-sm-13')
    links = [link.find('a').attrs["href"] for link in titles]
    
    with open("/content/citynews.json", 'a') as f:
        for link in links:
            news = requests.get(link)
            soup = BeautifulSoup(news.content, "html.parser")
            try:
              title = soup.find("h1", class_ = "headline").text
              data = {
                      "article_link" : link,
                      "headline" : title,
                      "is_sarcastic" : 0
                  }
              print(title)
              json.dump(data, f)
              f.write("\n")
            except:
              continue

import pandas as pd
data_js = pd.read_json('/content/citynews.json', lines= True)
data_js